# Generated by Django 3.2.7 on 2021-11-23 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('picture', models.FileField(blank=True, upload_to='images/')),
                ('region', models.CharField(choices=[('oakland', 'oakland'), ('squirrel', 'squirrel'), ('shadyside', 'shadyside')], max_length=50)),
                ('room_type', models.CharField(choices=[('studio', 'studio'), ('2b1b', '2b1b'), ('2b2b', '2b2b'), ('3b1b', '3b1b'), ('3b2b', '3b2b'), ('3b3b', '3b3b'), ('others', 'others')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('house_type', models.CharField(choices=[('house', 'house'), ('apartment', 'apartment')], max_length=50)),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('distance2cmu', models.FloatField()),
                ('latitude', models.FloatField(default=40.4433)),
                ('longtitude', models.FloatField(default=-79.9436)),
                ('posted_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_name', models.CharField(default=None, max_length=200)),
                ('user2_name', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Msg_str',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('profile_picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(max_length=50)),
                ('msg_box_list', models.ManyToManyField(related_name='msg_box_list', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('comment_date_time', models.DateTimeField()),
                ('self_box', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='housing.messagebox')),
                ('texted_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='messagebox',
            name='user1_user2_str',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='housing.msg_str'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('hprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.hprofile')),
            ],
        ),
    ]
